# Generated by Django 4.2.4 on 2023-09-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_category_category_caty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='caty',
            new_name='category',
        ),
    ]
