# Generated by Django 4.2.4 on 2023-09-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
